name: Twitter Collector

on:
  schedule:
    - cron: '0 * * * *'   # Runs every hour
  workflow_dispatch:       # Allows manual trigger from Actions tab

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        run: python collector.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Add tweets collected on $(date)"
          git push
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
